AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01103fb68b3569475
      InstanceType: t2.micro
      KeyName: cfn-key-1
