AWSTemplateFormatVersion: 2010-09-09
Description: Writing my own CF Templates

Resources:
  KKCFEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00c6c849418b7612c
      InstanceType: t2.micro
      KeyName: cfn-key-1
      SecurityGroups:
      - default
      - !Ref AllowSSHSecurityGroup
      Tags:
      - Key: Name
        Value: KkCf_EC2_Instance
      - Key: Owner
        Value: KK
  AllowSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG-to-allow-ssh
      GroupName: AllowSSH
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: TCP
        FromPort: 22
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        IpProtocol: ICMP
        FromPort: -1
        ToPort: -1
